name: testhelpredictor
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.19.2
  - pandas=1.1.3
  - python=3.8.6
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - statsmodels=0.12.0
  - threadpoolctl=2.1.0

